---
# PHP
- name: Add the ondrej PHP PPA
  apt_repository: repo='ppa:ondrej/php'

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Instal PHP
  apt: name={{item}} state=installed
  with_items:
    - php
    - php-fpm
    - php-mysql
    - php-xml
- name: Remove apache2
  apt : name=apache2 state=removed