---
- hosts: all
  become: true
  tasks:
    - name: Make sure we can connect
      ping:
    # PHP
    - name: Add the ondrej PHP PPA
      apt_repository: repo='ppa:ondrej/php'
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600
    - name: Instal PHP
      apt: name=php state=installed